const ENDPOINT_URL =  'http://localhost:9999'

export default {
    ENDPOINT_URL: ENDPOINT_URL,
    CUSTOMER_ENDPOINT_URL: `${ENDPOINT_URL}/customer`,
    RESTAURANT_ENDPOINT_URL: `${ENDPOINT_URL}/restaurant`,
    RESERVATION_ENDPOINT_URL: `${ENDPOINT_URL}/reservation`,
    RESTAURANT_TABLE_ENDPOINT_URL: `${ENDPOINT_URL}/restaurant-table`,
    BUTTON_COLOR: '#ff5e57',
    BUTTON_COLOR_HOVER: '#ff3b30',
    BACKGROUND_COLOR: '#ff726f'
}